services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Services
    Esit\Messagetoolbox\Classes\Services\ScopeHelper:
        public: true

    Esit\Messagetoolbox\Classes\Services\SessionMessage:
        public: true
        arguments:
            - "@session"

    # Wrapper
    Contao\FrontendTemplate: