# Services
services:
    esit_messagetoolbox.services.session.message:
        class: Esit\Messagetoolbox\Classes\Services\SessionMessage
        arguments: ["@session", "@esit_messagetoolbox.wrapper.frontend.template"]

    # Wrapper
    esit_messagetoolbox.wrapper.frontend.template:
        class: Contao\FrontendTemplate